###
GET http://localhost:3000/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJzZWFuLmRvZUBleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzIwMTA3NjcyfQ.YvF2NI0oTJv1QtT1PazfglrERBExuEWNIcgbFcO_nVY
###
GET http://localhost:3000/api/users/20

###

PUT http://localhost:3000/api/users/3
Content-Type: application/json

{
    "FullName": "John Doe",
    "role":"admin"
}

###
DELETE  http://localhost:3000/api/users/19


//end of user actions



//bookings
###
GET http://localhost:3000/api/bookings
###
DELETE  http://localhost:3000/api/bookings/3


###
GET http://localhost:3000/api/fleet

###
GET http://localhost:3000/api/fleet/2


///end of fleets
###
GET http://localhost:3000/api/locations

###
GET http://localhost:3000/api/payments

###
GET http://localhost:3000/api/vehicles




///vehiclespecs
###
GET http://localhost:3000/api/vehicle-specs



///end of vehiclespecs

###
GET http://localhost:3000/api/support-tickets

###
//authRouter
//admin
POST  http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "fullName": "Doe Miller",
    "email": "die.doe@example.com",
    "contactPhone": "+1234567890",
    "password": "password999",
    "address": "123 Main St, Anytown, USA",
    "role": "admin"
}

###
//authorized user
POST  http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "fullName": "SeanDoe Miller",
    "email": "sean.doe@example.com",
    "contactPhone": "+1234567890",
    "password": "password555",
    "address": "123 Main St, Anytown, USA",
    "role": "user"
}

###
//admin login
POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "die.doe@example.com",
    "password": "password999"
}
###
//user login
POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "sean.doe@example.com",
    "password": "password555"
}

//email testing
###
POST  http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "fullName": "Kennedy Mwangi",
    "email": "mwangiken128@gmail.com",
    "contactPhone": "+1234567890",
    "password": "12345678",
    "address": "123 Main St, Anytown, USA",
    "role": "admin"
}

###
POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "kennedymwaniki089@gmail.com",
    "password": "12345678"
}
